"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 5000

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status \
$nodejs\
$python\
$fill\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "blue"

[fill]
symbol = " "

[character]
success_symbol = '[❯](bold purple)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold green)'

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[nix_shell]
disabled = false

[nodejs]
symbol = "[⬢](bold green) "

